server:
  port: 8888
spring:
  datasource:
    continue-on-error: false
    name: dataSource
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:postgresql://172.18.73.72:5432/abase?charset=UTF8;appname=abase
    username: yjbl
    password: tusc@6789#JKL
    druid:
      initialSize: 50
      minIdle: 50
      maxActive: 50
      # 配置获取连接等待超时的时间
      maxWait: 60000
      testWhileIdle: true
      validationQuery: select version()
      #      validationQuery: select 1 from dual
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # Druid StatViewServlet监控配置
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: springboot
        login-password: 6123456
        allow: 127.0.0.1
        deny:
mybatis:
  type-aliases-package: com.prictice.bean
  mapperLocations: classpath:mapper/*Mapper.xml
swagger:
  enable: true
